<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Pentra.Application\Pentra.Application.csproj" />
    <ProjectReference Include="..\Pentra.Infrastructure\Pentra.Infrastructure.csproj" />
    <ProjectReference Include="..\Pentra.Domain\Pentra.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
